---
title: Siteleaf v2
url: http://v2.siteleaf.net
timezone: UTC
collections:
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    permalink: "/posts/:title/"
permalinks: pretty
twitter_username: siteleaf
exclude:
- node_modules
- config.ru
- Gemfile*
