---
title: Siteleaf v2
url: http://v2.siteleaf.com
timezone: UTC
collections:
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    permalink: "/blog/:title/"
    layout: post
description: Content management simplified. Edit in the cloud, publish anywhere. Supports
  static file output, any host, markdown, and multiple collaborators.
permalinks: pretty
twitter_username: siteleaf
exclude:
- node_modules
- config.ru
- Gemfile*
excerpt_separator: |2+



markdown: redcarpet
redcarpet:
  extensions:
  - autolink
  - fenced_code_blocks
  - lax_spacing
  - strikethrough
  - superscript
  - tables
  - footnotes
  - highlight
