---
title: Siteleaf v2
url: http://v2.siteleaf.com
timezone: America/New_York
collections:
  posts:
    title: Posts
    output: true
  tags:
    title: Tags
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    permalink: "/blog/:title/"
    layout: post
description: Content management simplified. Edit in the cloud, publish anywhere. Supports
  static file output, any host, markdown, and multiple collaborators.
permalinks: pretty
github_username: siteleaf
twitter_username: siteleaf
date_format: "%b %d, %Y"
exclude:
- Gruntfile.js
- package.json
- README*
- node_modules
- ".gitignore"
excerpt_separator: "\n\n"
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
# markdown: redcarpet
# redcarpet:
#   extensions:
#   - autolink
#   - fenced_code_blocks
#   - lax_spacing
#   - strikethrough
#   - superscript
#   - tables
#   - footnotes
#   - highlight
sass:
  sass_dir: styles/
  style: compressed
per_page: 10
