---
permalinks: pretty
twitter_username: siteleaf
title: Siteleaf v2
url: http://v2.siteleaf.com
timezone: UTC
collections:
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    permalink: "/posts/:title/"
