---
title: Siteleaf v2
timezone: America/New_York
collections:
  posts:
    title: Posts
    output: true
  tags:
    title: Tags
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    permalink: "/blog/:title/"
    layout: post
url: http://v2.siteleaf.com
description: Content management simplified. Edit in the cloud, publish anywhere. Supports
  static file output, any host, markdown, and multiple collaborators.
permalinks: pretty
exclude:
- Gruntfile.js
- package.json
- README*
- node_modules
- ".gitignore"
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
excerpt_separator: |2+



sass:
  sass_dir: styles/
  style: compressed
per_page: 12
date_format: "%b %d, %Y"
